requires:
   - https://github.com/moremoban/pypi-mobans
configuration:
  template_dir:
    - "pypi-mobans:templates"
    - local
  configuration: config.yml
targets:
  - mytravis.yml: travis.yml.jj2
  - test.txt: demo.txt.jj2
